
var EOL = require('os').EOL;

var HELP_TEXT = [
  '■ヘルパーのコマンド',
  '',
  '■■ヘルパーの使用方法を表示',
  'helper.help();',
  '',
  '  このコマンドです',
  '',
  '■■テストと同時にプロパティのコピー',
  'helper.copy(config, instance, properties);',
  '',
  '  propertiesを省略した場合はinstanceのクラスに定義されたプロパティ情報から',
  '  自動的に設定します',
  '',
  '■■クラスヘルパーの作成',
  'var classHelper = helper.of(Klass)',
  '',
  '■■カスタムヘルパーの作成',
  'var classHelper = helper(properties, template)',
  '',
  '',
  '■クラスヘルパーのコマンド',
  '',
  '■■テンプレートの表示',
  'classHelper.template();',
  '',
  '■■プロパティの一覧表示',
  'classHelper.property();',
  '',
  '■■指定プロパティの詳細表示',
  'classHelper.property(propertyName);',
  '',
  '■■指定プロパティのヘルパーを取得',
  'var otherClassHelper = classHelper.of(propertyName);',
  '',
  '■■ 初期化引数のテスト',
  'var pass = classHelper.test(config);',
  '',
  '  テスト成功でtrueを返します',
  ''
].join(EOL);

module.exports = exports = HELP_TEXT;
